name: x86-64

on: [ push, pull_request ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-24.04, macos-13 ]
        cpu_detection: [ 0, 1 ]
      fail-fast: false

    runs-on: ${{matrix.os}}

    steps:

      - name: Install build dependencies
        if: ${{matrix.os == 'ubuntu-24.04'}}
        run: sudo apt-get install llvm ninja-build gcc-13 g++-13

      - name: Install build dependencies
        if: ${{matrix.os == 'macos-13'}}
        run: |
          brew install llvm ninja
          echo "/usr/local/opt/llvm/bin" >> $GITHUB_PATH

      - name: Setup XCode
        if: ${{matrix.os == 'macos-13'}}
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Checkout dynarmic repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build unicorn
        if: ${{matrix.os == 'ubuntu-24.04' || matrix.os == 'macos-13'}}
        working-directory: externals/unicorn
        run: UNICORN_ARCHS=aarch64,arm ./make.sh

      - name: Configure CMake
        if: ${{matrix.os == 'ubuntu-24.04'}}
        env:
          CC: gcc-13
          CXX: g++-13
          CXXFLAGS: -Wp,-D_GLIBCXX_ASSERTIONS
        run: >
          cmake
          -B ${{github.workspace}}/build
          -DCMAKE_CXX_FLAGS="-std=c++20"
          -DBOOST_INCLUDEDIR=${{github.workspace}}/externals/ext-boost
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          -DDYNARMIC_ENABLE_CPU_FEATURE_DETECTION=${{matrix.cpu_detection}}
          -DDYNARMIC_TESTS_USE_UNICORN=1
          -DDYNARMIC_USE_LLVM=1
          -DLIBUNICORN_INCLUDE_DIR=${{github.workspace}}/externals/unicorn/include
          -DLIBUNICORN_LIBRARY=${{github.workspace}}/externals/unicorn/libunicorn.a
          -G Ninja

      - name: Configure CMake
        if: ${{matrix.os == 'macos-13'}}
        run: >
          cmake
          -B ${{github.workspace}}/build
          -DCMAKE_CXX_FLAGS="-std=c++20"
          -DBOOST_INCLUDEDIR=${{github.workspace}}/externals/ext-boost
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          -DDYNARMIC_ENABLE_CPU_FEATURE_DETECTION=${{matrix.cpu_detection}}
          -DDYNARMIC_TESTS_USE_UNICORN=1
          -DDYNARMIC_USE_LLVM=1
          -DLIBUNICORN_INCLUDE_DIR=${{github.workspace}}/externals/unicorn/include
          -DLIBUNICORN_LIBRARY=${{github.workspace}}/externals/unicorn/libunicorn.a
          -G Ninja

      - name: Configure CMake
        if: ${{matrix.os == 'windows-latest'}}
        run: >
          cmake
          -B ${{github.workspace}}/build
          -DCMAKE_CXX_FLAGS="/std:c++20"
          -DBOOST_INCLUDEDIR=${{github.workspace}}/externals/ext-boost
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          -DDYNARMIC_ENABLE_CPU_FEATURE_DETECTION=${{matrix.cpu_detection}}
          -G "Visual Studio 17 2022"
          -A x64

      - name: Build
        working-directory: ${{github.workspace}}/build
        run: cmake --build . --config Release

      - name: Test
        env:
          DYLD_FALLBACK_LIBRARY_PATH: ${{github.workspace}}/externals/unicorn
        working-directory: ${{github.workspace}}/build
        run: ctest --extra-verbose -C ${{env.BUILD_TYPE}}
